### ISSUE TITLE
sqlite3.OperationalError: RIGHT and FULL OUTER JOINs are not currently supported

### ISSUE THREAD

**Issue by fullstackwebdev** [Pleias/pleias_ScholasticAI#5]
```
 python -m src.main
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Unknown property text-underline-position
Unknown property text-decoration-skip-ink
Initializing the model...
Fetching 30 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 12266.44it/s]
You're using a XLMRobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
Traceback (most recent call last):
  File "/home/fullstack/dev/pleias_ScholasticAI/src/main.py", line 119, in get_response
    references_info, html_output = get_response_and_metadata(
  File "/home/fullstack/dev/pleias_ScholasticAI/src/core/get_answer_from_api.py", line 327, in get_response_and_metadata
    results = retrieve(connection, user_message)
  File "/home/fullstack/dev/pleias_ScholasticAI/src/core/RAG.py", line 114, in retrieve
    cursor.execute(
sqlite3.OperationalError: RIGHT and FULL OUTER JOINs are not currently supported



```

Getting this error on hello world chat on startup.

**Comment by matthieudelsart** [comment]
Hello,

This is probably due to an outdated version of sqlite3 on your side as RIGHT and FULL OUTER JOINs are now supported by sqlite3.
We updated the requirements with a recent version of sqlite3, could you let us if this solves your error?

Thanks
