### ISSUE TITLE
fitz

### ISSUE THREAD

**Issue by victorca25** [Pleias/pleias_ScholasticAI#6]
There seems to be an issue with having fitz and pymupdf both in the Python environment, 
fitz==0.0.1.dev2
pymupdf==1.24.11

Both use the `fitz` name and the application fails to load when both are installed, at least on Mac:

`
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/pleias_ScholasticAI/src/main.py", line 10, in <module>
    from src.core.connect_db import ConnectDB
  File "/pleias_ScholasticAI/src/core/connect_db.py", line 8, in <module>
    from src.core.pdf_processing_pipeline import process_pdfs_in_folder
  File "/pleias_ScholasticAI/src/core/pdf_processing_pipeline.py", line 16, in <module>
    import fitz  # PyMuPDF
    ^^^^^^^^^^^
  File "/pleias_ScholasticAI/venv/lib/python3.12/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'
`

This corresponds to what is mentioned here: https://stackoverflow.com/questions/56467667/how-do-i-resolve-no-module-named-frontend-error-message, but removing `fitz==0.0.1.dev2` makes the code fail later, when the other fitz is expected:

`
Step 3: Text Extraction...
Unloading YOLO model...
Traceback (most recent call last):
  File "/pleias_ScholasticAI/src/main.py", line 215, in upload_files
    self.db.parse_pdf_to_db()
  File "/pleias_ScholasticAI/src/core/connect_db.py", line 245, in parse_pdf_to_db
    parsed_pdf_list = process_pdfs_in_folder(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/pleias_ScholasticAI/src/core/pdf_processing_pipeline.py", line 778, in process_pdfs_in_folder
    total_files, text_extraction_time, _ = process_directory_for_text_extraction(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pleias_ScholasticAI/src/core/pdf_processing_pipeline.py", line 456, in process_directory_for_text_extraction
    processing_time, tsv_files_produced = process_all_pages_parallel(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pleias_ScholasticAI/src/core/pdf_processing_pipeline.py", line 426, in process_all_pages_parallel
    doc = fitz.open(pdf_path)
          ^^^^^^^^^
AttributeError: module 'fitz' has no attribute 'open'
`

Note that fitz==0.0.1.dev2 seems to be abandoned: https://github.com/kastman/fitz and probably should be avoided

**Comment by victorca25** [comment]
Replacing all the `fitz` in:
https://github.com/Pleias/pleias_ScholasticAI/blob/4ebc929aefcc35cc7255a43ebf9356d139754fc9/src/core/pdf_processing_pipeline.py#L16

for:
`import pymupdf as fitz`

helps, now the application didn't fail at that step

**Comment by rosas-h** [comment]
Hello! Thanks for your observations. You're right, I updated both the import and also simplified requirements.txt
