### ISSUE TITLE
sqlite3.OperationalError: fts5: syntax error near ","

### ISSUE THREAD

**Issue by jbl2024** [Pleias/pleias_ScholasticAI#7]
Description: When attempting to execute any queries in the application, the following error is raised:

```
Traceback (most recent call last):
  File "./pleias_ScholasticAI/src/main.py", line 119, in get_response
    references_info, html_output = get_response_and_metadata(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./pleias_ScholasticAI/src/core/get_answer_from_api.py", line 327, in get_response_and_metadata
    results = retrieve(connection, user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./pleias_ScholasticAI/src/core/RAG.py", line 114, in retrieve
    cursor.execute(
sqlite3.OperationalError: fts5: syntax error near ","
```

Environment Details:
- Python version : 3.11.11
- SQLite version (system): 3.47.2
- SQLite version (Python): 3.47.2 (`python -c "import sqlite3; print(sqlite3.sqlite_version)"`)

Note: Python and SQLite are managed with asdf, on Macos 15.1.1 (24B91)

**Comment by jbl2024** [comment]
Note: It happens when query contains special characters ("?", "!")
