### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. 

### ISSUE THREAD

**Issue by mchaduteau** [Pleias/pleias_ScholasticAI#9]
When uploading a PDF file, I get the following error and trace back:

Step 1: Processing PDFs...
Processing PDFs: 100%|█████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 336.18it/s]
Total pages processed: 64
Total processing time: 4.32 seconds
Average time per page: 0.07 seconds/page
PDF processing completed.

Step 2: Processing Images...
Loading YOLO model...

0: 640x480 3 MainZone-Heads, 14 MainZone-Lists, 5 MainZone-Ps, 1 NumberingZone, 6.7ms
1: 640x480 3 MainZone-Lists, 11 MainZone-Ps, 1 MarginTextZone-Notes, 1 NumberingZone, 6.7ms
2: 640x480 4 MainZone-Heads, 10 MainZone-Ps, 4 MarginTextZone-Notess, 1 NumberingZone, 6.7ms
3: 640x480 4 MainZone-Heads, 3 MainZone-Lists, 6 MainZone-Ps, 3 MarginTextZone-Notess, 2 NumberingZones, 1 RunningTitleZone, 6.7ms
4: 640x480 1 MainZone-Entry, 2 MainZone-Heads, 2 MainZone-Lists, 9 MainZone-Ps, 1 MainZone-P-Continued, 9 MarginTextZone-Notess, 1 NumberingZone, 6.7ms
5: 640x480 1 MainZone-Head, 9 MainZone-Ps, 1 MainZone-P-Continued, 5 MarginTextZone-Notess, 2 NumberingZones, 6.7ms
6: 640x480 9 MainZone-Ps, 3 MarginTextZone-Notess, 1 NumberingZone, 6.7ms
7: 640x480 1 TableZone, 6.7ms
8: 640x480 1 MainZone-Head, 4 MainZone-Lists, 7 MainZone-Ps, 2 MarginTextZone-Notess, 1 NumberingZone, 6.7ms
9: 640x480 1 MainZone-Head, 1 PageTitleZone-Index, 6.7ms
Speed: 1.4ms preprocess, 6.7ms inference, 21.8ms postprocess per image at shape (1, 3, 640, 480)
Unloading YOLO model...
Traceback (most recent call last):
  File "/home/mcc/pleias_ScholasticAI/src/main.py", line 215, in upload_files
    self.db.parse_pdf_to_db()
  File "/home/mcc/pleias_ScholasticAI/src/core/connect_db.py", line 245, in parse_pdf_to_db
    parsed_pdf_list = process_pdfs_in_folder(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcc/pleias_ScholasticAI/src/core/pdf_processing_pipeline.py", line 771, in process_pdfs_in_folder
    total_images, image_processing_time, avg_image_time = process_images_directory(
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcc/pleias_ScholasticAI/src/core/pdf_processing_pipeline.py", line 259, in process_images_directory
    images_processed, time_spent = process_images_in_output_folder(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcc/pleias_ScholasticAI/src/core/pdf_processing_pipeline.py", line 242, in process_images_in_output_folder
    process_image_batch(batch, results_yolo_folder, model_path)
  File "/home/mcc/pleias_ScholasticAI/src/core/pdf_processing_pipeline.py", line 192, in process_image_batch
    boxes = result.boxes.xyxy.numpy()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by mchaduteau** [comment]
Anybody listening on the other side?
